### ISSUE TITLE
Application error An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command heroku logs --tail

### ISSUE THREAD

**Issue by rohinidev-bit** [kimlimjustin/google-form-clone#39]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rohinidev-bit** [comment]
It was running fine few weeks ago.

**Comment by kimlimjustin** [comment]
See #9. 

The quick answer is I got no money to pay Heroku and they have limits (550 hours a month) and that's why it's always down every the end of the month. It's highly recommended to host it by yourself remembering there's already a docker file.
