### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Dadenn** [kimlimjustin/google-form-clone#5]
How can we get the source code

**Comment by kimlimjustin** [comment]
The source code is available on the ["code"](https://github.com/kimlimjustin/google-form-clone/tree/master) section. If the system doesn't show you the code, please click the browse file.

**Comment by Dadenn** [comment]
Is there a way for me to bring it on to tampermonkey?

**Comment by kimlimjustin** [comment]
> Is there a way for me to bring it on to tampermonkey?

What do you mean?  this google forms clone is website based. (here's the link: https://google-forms-clone.herokuapp.com/). Tampermonkey is script plugin, isn't it?
